hash  := $(shell git rev-parse --short HEAD)
type  := mv mz
verfn := cheat-engine/www/cheat/version.js
verjs := export const RPGVERSION = "$(hash)" /* autogenerated by Makefile */
shiki := cheat-engine/www/cheat/libs/shiki.bundle.mjs
vue   := cheat-engine/www/cheat/libs/vue.js
vuetify := cheat-engine/www/cheat/libs/vuetify.js
vuetifycss := cheat-engine/www/cheat/css/vuetify.css
mdicss := cheat-engine/www/cheat/css/materialdesignicons.css
mdifonts := cheat-engine/www/cheat/fonts/materialdesignicons-webfont.woff2

.PHONY: all clean vendor $(type)

all: $(type)

vendor: $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss) $(mdifonts)

$(shiki):
	pnpm run vendor:shiki

$(vuetify):
	pnpm run vendor:vuetify

$(vue):
	pnpm run vendor:vue

$(vuetifycss) $(mdicss) $(mdifonts):
	pnpm run vendor:assets

clean:
	-rm -f *.tar.gz *-latest.tar.gz $(verfn) $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss)
	-rm -f cheat-engine/www/cheat/fonts/materialdesignicons-webfont.*

%-$(hash).tar.gz: $(verfn) $(shiki) $(vuetify) $(vue) $(vuetifycss) $(mdicss) $(mdifonts)
	GZIP=-9 COPYFILE_DISABLE=1 tar --exclude='*DS_Store' -czvf $@ \
		-C cheat-engine/www cheat \
		-C _cheat_initialize/$* js
	ln -s -f $@ $*-latest.tar.gz

$(type):%:%-$(hash).tar.gz
	@echo finished packing $@

$(verfn):
	printf '%s\n' '$(verjs)' > $(verfn)
